# Generated by Django 2.0.10 on 2019-04-07 21:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('courseID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('courseTitle', models.CharField(max_length=200)),
                ('courseDesc', models.TextField()),
                ('createAt', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'courses',
            },
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='db.Course')),
            ],
            options={
                'db_table': 'courseEnrollment',
            },
        ),
        migrations.CreateModel(
            name='CourseTA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='db.Course')),
            ],
            options={
                'db_table': 'courseTA',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('facultyId', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('facultyName', models.CharField(max_length=50)),
                ('facultyDesignation', models.CharField(max_length=50)),
                ('facultyAreaOfInterest', models.TextField(max_length=1000, null=True)),
            ],
            options={
                'db_table': 'faculty',
            },
        ),
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labNumber', models.CharField(max_length=20)),
                ('marksObtained', models.FloatField()),
                ('maxMarks', models.FloatField()),
                ('courseId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='db.Course')),
            ],
            options={
                'db_table': 'grades',
            },
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=40)),
                ('role', models.CharField(max_length=10)),
                ('userId', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'login',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentRollNo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('studentName', models.CharField(max_length=60)),
                ('studentClass', models.CharField(max_length=10)),
                ('studentYear', models.SmallIntegerField()),
                ('studentSem', models.CharField(max_length=4)),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.AddField(
            model_name='grades',
            name='studentRollNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='db.Student'),
        ),
        migrations.AddField(
            model_name='courseta',
            name='studentRollNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='db.Student'),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='studentRollNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='db.Student'),
        ),
        migrations.AddField(
            model_name='course',
            name='courseInstructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='db.Faculty'),
        ),
        migrations.AlterUniqueTogether(
            name='grades',
            unique_together={('studentRollNo', 'courseId', 'labNumber')},
        ),
        migrations.AlterUniqueTogether(
            name='courseta',
            unique_together={('studentRollNo', 'courseId')},
        ),
        migrations.AlterUniqueTogether(
            name='courseenrollment',
            unique_together={('studentRollNo', 'courseId')},
        ),
    ]
